# pnpm workspace configuration
# Similar to UV's pyproject.toml workspace management for Python
# See: https://pnpm.io/workspaces

packages:
  # Include the repository root so shared tooling installs correctly
  - '.'
  # Future Node.js packages would go here
  - 'packages/*'
  - 'tools/*'
  - '!**/test/**'
